# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

services:
  haproxy:
    container_name: haproxy-frontend
    image: haproxy:alpine
    restart: always
    depends_on:
      proxy:
        condition: service_healthy
    ports:
      - "80:80" 
      - "443:443"
    networks:
      - default
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"

  proxy:
    depends_on:
      generate-certs:
        condition: service_completed_successfully

    container_name: proxy
    image: quay.io/jupyterhub/configurable-http-proxy:4
    restart: always
    environment:
      CONFIGPROXY_AUTH_TOKEN: ${CONFIGPROXY_AUTH_TOKEN}
      PYTHONUNBUFFERED: "1"
    volumes:
      - "ssl:${SSL_VOLUME_CONTAINER}:ro"
    user: "0:0"
    networks:
      default:
        aliases:
          - proxy
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:8443/_chp_healthz"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: >
      configurable-http-proxy
      --port 8443
      --ssl-key ${SSL_VOLUME_CONTAINER}/certs/proxy-client/proxy-client.key
      --ssl-cert ${SSL_VOLUME_CONTAINER}/certs/proxy-client/proxy-client.crt
      --api-ip 0.0.0.0
      --api-port 8001
      --error-target https://jupyterhub:8081/hub/error
      --api-ssl-key ${SSL_VOLUME_CONTAINER}/certs/proxy-api/proxy-api.key
      --api-ssl-cert ${SSL_VOLUME_CONTAINER}/certs/proxy-api/proxy-api.crt
      --api-ssl-ca ${SSL_VOLUME_CONTAINER}/certs/proxy-api-ca_trust.crt
      --api-ssl-request-cert
      --api-ssl-reject-unauthorized
      --client-ssl-key ${SSL_VOLUME_CONTAINER}/certs/proxy-client/proxy-client.key
      --client-ssl-cert ${SSL_VOLUME_CONTAINER}/certs/proxy-client/proxy-client.crt
      --client-ssl-ca ${SSL_VOLUME_CONTAINER}/certs/proxy-client-ca_trust.crt
      --client-ssl-request-cert
      --client-ssl-reject-unauthorized

  # this is identical to the hub service
  # but runs the `--generate-certs` step first
  generate-certs:
    user: "0:0"
    build:
      context: images/jupyterhub
      dockerfile: Dockerfile
    restart: "no"
    image: jupyterhub/jupyterhub:internal-ssl
    volumes:
      - "ssl:${SSL_VOLUME_CONTAINER}:rw"
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
    environment:
      PYTHONUNBUFFERED: "1"
      CONFIGPROXY_AUTH_TOKEN: ${CONFIGPROXY_AUTH_TOKEN}
      # All containers will join this network
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: ${DOCKER_NOTEBOOK_IMAGE}
      # SSL path
      INTERNAL_SSL_PATH: ${SSL_VOLUME_CONTAINER}/certs
    working_dir: ${DATA_VOLUME_CONTAINER}
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py --generate-certs

  hub:
    user: "0:0"
    depends_on:
      proxy:
        condition: service_healthy
      generate-certs:
        condition: service_completed_successfully
    build:
      context: images/jupyterhub
      dockerfile: Dockerfile
    restart: always
    image: jupyterhub:internal-ssl
    container_name: jupyterhub
    networks:
      default:
        aliases:
          - jupyterhub
    volumes:
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "data:${DATA_VOLUME_CONTAINER}:rw"
      - "ssl:${SSL_VOLUME_CONTAINER}:rw"
      - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
      - "./volume:/data"
    environment:
      PYTHONUNBUFFERED: "1"
      CONFIGPROXY_AUTH_TOKEN: ${CONFIGPROXY_AUTH_TOKEN}
      # All containers will join this network
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}
      # JupyterHub will spawn this Notebook image for users
      DOCKER_NOTEBOOK_IMAGE: ${DOCKER_NOTEBOOK_IMAGE}
      # SSL path
      INTERNAL_SSL_PATH: ${SSL_VOLUME_CONTAINER}/certs
      # This username will be a JupyterHub admin
      JUPYTERHUB_ADMIN: ${JUPYTERHUB_ADMIN}
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: ${DOCKER_NOTEBOOK_DIR}
      # Absolute path on host where user data will be stored
      HOST_DATA_DIR: ${PWD}/volume
      # Enable GPU support (1 = enabled, 0 = disabled)
      ENABLE_GPU: ${ENABLE_GPU:-0}
    working_dir: ${DATA_VOLUME_CONTAINER}
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py

volumes:
  data:
    name: ${DATA_VOLUME_HOST}
    external: true
  ssl:
    name: ${SSL_VOLUME_HOST}
    external: true

networks:
  default:
    name: ${DOCKER_NETWORK_NAME}
    external: true
